import crypto from 'node:crypto';
import { SignJWT, jwtVerify, createRemoteJWKSet } from 'jose';
import { upsertUser, getUserByEmail, getApiKeyByHash } from './store.mjs';

const SESSION_COOKIE='lfds_session';const FLOW_COOKIE='lfds_oauth_flow';
const secretBytes=()=>new TextEncoder().encode(process.env.AUTH_SECRET||process.env.APP_ACCESS_CODE||'lfds-development-change-me');
const baseUrl=req=>process.env.PUBLIC_BASE_URL||`${req.protocol}://${req.get('host')}`;
const parseCookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [decodeURIComponent(i<0?x:x.slice(0,i)),decodeURIComponent(i<0?'':x.slice(i+1))]}));
function setCookie(res,name,value,{maxAge=3600,httpOnly=true}={}){const prod=process.env.NODE_ENV==='production';res.append('Set-Cookie',`${name}=${encodeURIComponent(value)}; Path=/; Max-Age=${maxAge}; SameSite=Lax${httpOnly?'; HttpOnly':''}${prod?'; Secure':''}`)}
function clearCookie(res,name){const prod=process.env.NODE_ENV==='production';res.append('Set-Cookie',`${name}=; Path=/; Max-Age=0; SameSite=Lax; HttpOnly${prod?'; Secure':''}`)}
function providerConfig(provider){if(provider==='google'&&process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET)return {id:'google',clientId:process.env.GOOGLE_CLIENT_ID,clientSecret:process.env.GOOGLE_CLIENT_SECRET,discovery:'https://accounts.google.com/.well-known/openid-configuration'};if(provider==='microsoft'&&process.env.MICROSOFT_CLIENT_ID&&process.env.MICROSOFT_CLIENT_SECRET){const tenant=process.env.MICROSOFT_TENANT_ID||'organizations';return {id:'microsoft',clientId:process.env.MICROSOFT_CLIENT_ID,clientSecret:process.env.MICROSOFT_CLIENT_SECRET,discovery:`https://login.microsoftonline.com/${tenant}/v2.0/.well-known/openid-configuration`}}return null}
const discoveryCache=new Map();async function discovery(cfg){if(discoveryCache.has(cfg.discovery))return discoveryCache.get(cfg.discovery);const r=await fetch(cfg.discovery);if(!r.ok)throw new Error('Could not load identity provider configuration.');const d=await r.json();discoveryCache.set(cfg.discovery,d);return d}
function b64url(buf){return Buffer.from(buf).toString('base64url')}
function roleForEmail(email){email=String(email).toLowerCase();const lists=[['admin','ADMIN_EMAILS'],['approver','APPROVER_EMAILS'],['reviewer','REVIEWER_EMAILS']];for(const[r,k]of lists)if(String(process.env[k]||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).includes(email))return r;return 'creator'}
function emailAllowed(email){const domains=String(process.env.ALLOWED_EMAIL_DOMAINS||'recykal.com').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return !domains.length||domains.some(d=>String(email).toLowerCase().endsWith(`@${d}`))}
export function authCapabilities(){return {google:Boolean(providerConfig('google')),microsoft:Boolean(providerConfig('microsoft')),accessCode:Boolean(process.env.APP_ACCESS_CODE),scim:Boolean(process.env.SCIM_BEARER_TOKEN),rbac:true}}
export async function beginOidc(req,res,provider){const cfg=providerConfig(provider);if(!cfg)return res.status(404).send('Identity provider is not configured.');const d=await discovery(cfg);const state=b64url(crypto.randomBytes(24)),nonce=b64url(crypto.randomBytes(24)),verifier=b64url(crypto.randomBytes(48)),challenge=b64url(crypto.createHash('sha256').update(verifier).digest());const flow=await new SignJWT({provider,state,nonce,verifier}).setProtectedHeader({alg:'HS256'}).setIssuedAt().setExpirationTime('10m').sign(secretBytes());setCookie(res,FLOW_COOKIE,flow,{maxAge:600});const redirectUri=`${baseUrl(req)}/auth/callback/${provider}`;const u=new URL(d.authorization_endpoint);u.searchParams.set('client_id',cfg.clientId);u.searchParams.set('response_type','code');u.searchParams.set('redirect_uri',redirectUri);u.searchParams.set('scope','openid profile email');u.searchParams.set('state',state);u.searchParams.set('nonce',nonce);u.searchParams.set('code_challenge',challenge);u.searchParams.set('code_challenge_method','S256');u.searchParams.set('prompt','select_account');res.redirect(u.toString())}
export async function finishOidc(req,res,provider){const cfg=providerConfig(provider);if(!cfg)throw new Error('Identity provider is not configured.');const flowToken=parseCookies(req)[FLOW_COOKIE];if(!flowToken)throw new Error('Sign-in session expired.');const {payload:flow}=await jwtVerify(flowToken,secretBytes());if(flow.provider!==provider||flow.state!==req.query.state)throw new Error('Invalid sign-in state.');const d=await discovery(cfg);const redirectUri=`${baseUrl(req)}/auth/callback/${provider}`;const form=new URLSearchParams({grant_type:'authorization_code',code:String(req.query.code||''),redirect_uri:redirectUri,client_id:cfg.clientId,client_secret:cfg.clientSecret,code_verifier:String(flow.verifier)});const tr=await fetch(d.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});if(!tr.ok)throw new Error('Identity provider rejected the sign-in exchange.');const tokens=await tr.json();if(!tokens.id_token)throw new Error('No identity token returned.');const jwks=createRemoteJWKSet(new URL(d.jwks_uri));const {payload}=await jwtVerify(tokens.id_token,jwks,{audience:cfg.clientId,issuer:d.issuer});if(payload.nonce&&payload.nonce!==flow.nonce)throw new Error('Identity nonce mismatch.');const email=String(payload.email||payload.preferred_username||'').toLowerCase();if(!email||!emailAllowed(email))throw new Error('This account is not permitted to use the Recykal Studio.');const existing=await getUserByEmail(email);const user=await upsertUser({...(existing||{}),email,name:payload.name||existing?.name||email,role:existing?.role||roleForEmail(email),provider,externalId:String(payload.sub||''),active:existing?.active!==false,data:{tenantId:payload.tid||null,picture:payload.picture||null}});if(!user.active)throw new Error('This user has been disabled.');const session=await new SignJWT({sub:user.id,email:user.email,name:user.name,role:user.role,provider:user.provider}).setProtectedHeader({alg:'HS256'}).setIssuedAt().setExpirationTime('12h').sign(secretBytes());setCookie(res,SESSION_COOKIE,session,{maxAge:43200});clearCookie(res,FLOW_COOKIE);res.redirect('/')}
export function logout(res){clearCookie(res,SESSION_COOKIE);clearCookie(res,FLOW_COOKIE)}
export async function requestIdentity(req){const cookies=parseCookies(req);if(cookies[SESSION_COOKIE]){try{const {payload}=await jwtVerify(cookies[SESSION_COOKIE],secretBytes());return {kind:'session',id:payload.sub,email:payload.email,name:payload.name,role:payload.role||'creator',provider:payload.provider||'session'}}catch{}}
  const auth=String(req.get('authorization')||'');if(auth.startsWith('Bearer lfs_')){const raw=auth.slice(7);const key=await getApiKeyByHash(crypto.createHash('sha256').update(raw).digest('hex'));if(key)return {kind:'api-key',id:key.id,name:key.name,role:'api',scopes:key.scopes||[]}}
  const expected=process.env.APP_ACCESS_CODE;if(expected&&req.get('x-access-code')===expected)return {kind:'access-code',id:'legacy-team',name:'Marketing Team',email:'',role:'admin',provider:'access-code'};
  if(!expected&&!providerConfig('google')&&!providerConfig('microsoft'))return {kind:'development',id:'dev',name:'Marketing Team',role:'admin'};return null}
const roleRank={viewer:0,creator:1,reviewer:2,approver:3,admin:4,api:0};
export function hasRole(identity,required='viewer'){if(identity?.kind==='api-key')return false;return (roleRank[identity?.role]??-1)>=(roleRank[required]??0)}
export function requireRole(required){return async(req,res,next)=>{const id=req.identity||await requestIdentity(req);if(!id)return res.status(401).json({error:'Sign in required.'});if(!hasRole(id,required))return res.status(403).json({error:`${required} role required.`});req.identity=id;next()}}
export async function requireAuthenticated(req,res,next){const id=await requestIdentity(req);if(!id)return res.status(401).json({error:'Sign in required.'});req.identity=id;next()}
export function scimAuthorized(req){const token=String(process.env.SCIM_BEARER_TOKEN||'');return Boolean(token)&&String(req.get('authorization')||'')===`Bearer ${token}`}
export function newApiKey(){return `lfs_${b64url(crypto.randomBytes(32))}`}
export function hashKey(raw){return crypto.createHash('sha256').update(raw).digest('hex')}
