import { listUsers, upsertUser, patchUser, deactivateUser } from './store.mjs';
const base='urn:ietf:params:scim:schemas:core:2.0:User';
function scimUser(u){return {schemas:[base],id:u.id,userName:u.email,active:u.active!==false,displayName:u.name,name:{formatted:u.name},emails:[{value:u.email,primary:true,type:'work'}],roles:[{value:u.role,primary:true}],meta:{resourceType:'User',created:u.createdAt,lastModified:u.updatedAt}}}
export async function listScim(req,res){const all=(await listUsers()).filter(u=>!req.query.filter||String(req.query.filter).includes(u.email));res.json({schemas:['urn:ietf:params:scim:api:messages:2.0:ListResponse'],totalResults:all.length,startIndex:1,itemsPerPage:all.length,Resources:all.map(scimUser)})}
export async function createScim(req,res){const b=req.body||{};const email=String(b.userName||b.emails?.[0]?.value||'').toLowerCase();if(!email)return res.status(400).json({detail:'userName/email is required.'});const user=await upsertUser({email,name:b.displayName||b.name?.formatted||email,role:b.roles?.[0]?.value||'creator',provider:'scim',active:b.active!==false});res.status(201).json(scimUser(user))}
export async function getScim(req,res){const u=(await listUsers()).find(x=>x.id===req.params.id);if(!u)return res.status(404).json({detail:'User not found.'});res.json(scimUser(u))}
export async function replaceScim(req,res){const current=(await listUsers()).find(x=>x.id===req.params.id);if(!current)return res.status(404).json({detail:'User not found.'});const b=req.body||{};const user=await patchUser(current.id,{name:b.displayName||b.name?.formatted||current.name,role:b.roles?.[0]?.value||current.role,active:b.active!==false});res.json(scimUser(user))}
export async function patchScim(req,res){const current=(await listUsers()).find(x=>x.id===req.params.id);if(!current)return res.status(404).json({detail:'User not found.'});const patch={};for(const op of req.body?.Operations||[]){const path=String(op.path||'').toLowerCase();if(path==='active')patch.active=Boolean(op.value);if(path==='displayname'||path==='name.formatted')patch.name=String(op.value||'');if(path==='roles'||path==='roles.value')patch.role=Array.isArray(op.value)?String(op.value[0]?.value||op.value[0]||'creator'):String(op.value||'creator')}const user=await patchUser(current.id,patch);res.json(scimUser(user))}
export async function deleteScim(req,res){await deactivateUser(req.params.id);res.status(204).end()}
